fileupload
jnm92/geowave pull request #14
Opened 2017-03-31 15:59 UTC by Becca42

2017-03-31 18:06 UTC, mak438 requested changes

2017-03-31 18:06 UTC, mak438 commented on services/rest/src/main/java/mil/nga/giat/geowave/service/rest/RestServer.java
> +	public class FileUploadServerResource extends
Annotate this class with @GeowaveOperation, so that the RestServer startup code can find it.

2017-03-31 18:06 UTC, mak438 commented on services/rest/src/main/java/mil/nga/giat/geowave/service/rest/RestServer.java
> +						result = new StringRepresentation(
Return a json object, for consistency with the other commands.

2017-04-23 16:45 UTC, mak438 commented
Where will this be storing the file?

2017-04-24 02:20 UTC, Becca42 commented
So accept (the post function) returns a string representation of the file's contents.

2017-05-08 02:15 UTC, closed without merging