geowave/config/addindex and geowave/config/copyindex
jnm92/geowave pull request #19
Opened 2017-04-28 16:09 UTC by mrkev

👍

2017-04-28 19:49 UTC, mak438 requested changes

2017-04-28 19:49 UTC, mak438 commented on core/store/src/main/java/mil/nga/giat/geowave/core/store/operations/config/AddIndexCommand.java
> +	public void readFormArgs(
Remove. DefaultOperation reads the form args automatically now.

2017-04-28 19:49 UTC, mak438 commented on core/store/src/main/java/mil/nga/giat/geowave/core/store/operations/config/CopyIndexCommand.java
>  	public void readFormArgs(
Remove. DefaultOperation reads the form args automatically now.

2017-04-28 19:49 UTC, mak438 commented on core/store/src/main/java/mil/nga/giat/geowave/core/store/operations/remote/options/IndexPluginOptions.java
> +	public void setNumPartitions(
I don't see where these are used. Are they needed?

2017-04-28 19:49 UTC, mak438 commented on services/rest/src/test/java/mil/nga/giat/geowave/service/rest/RestServerTest.java
> +	// @Ignore("Kevin will fix addindex")
Remove this line.

2017-05-03 17:27 UTC, mak438 approved these changes

2017-05-03 17:28 UTC, mak438 commented
Please squash if you can.

2017-05-03 22:01 UTC, mrkev commented
@mak438 Github can squash automatically when you merge a PR, it's one of the options of the merge button

2017-05-03 22:02 UTC, mrkev commented
If you give me a thumbs up ill just squash and merge now

2017-05-03 22:04 UTC, mak438 commented
Go for it! :thumbsup:

2017-05-03 22:05 UTC, merged